name: mecaro
description: "mecaro test task"

publish_to: 'none' 


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.6

  flutter_extended_nmea: ^1.3.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/
